### ISSUE TITLE
Add Clean and Upload Jars tasks

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias-contrib#3]
There should be tasks to Clean all the Jars and another one to upload them to an artifactory.

**Comment by nicosingh** [comment]
I added Artifactory dependencies:

https://github.com/IntegratedAlarmSystem-Group/ias-plugins/blob/142737d0d90db70829343ee2ab80802d753b48a4/AlmaWeatherStationPlugin/build.gradle#L1-L14

And also defined project group and version:

https://github.com/IntegratedAlarmSystem-Group/ias-plugins/blob/142737d0d90db70829343ee2ab80802d753b48a4/AlmaWeatherStationPlugin/build.gradle#L16-L17

On the other hand, I added a new gradle task called **uploadArchives**, which uses this plugin to upload artifacts to Artifactory:

https://github.com/IntegratedAlarmSystem-Group/ias-plugins/blob/142737d0d90db70829343ee2ab80802d753b48a4/AlmaWeatherStationPlugin/build.gradle#L72-L82

Which is expecting Artifactory credentials as environment variables. These variables are mapped in our Jenkins job:

![image](https://user-images.githubusercontent.com/4417761/37421475-2b7855c6-2798-11e8-8c3f-76528a5270b3.png)

Finally, we defined an artifact name called **"alma-weather-station-plugin"**:

https://github.com/IntegratedAlarmSystem-Group/ias-plugins/blob/f2def430fb34c94b8b5b10e44649ba99b6d33816/AlmaWeatherStationPlugin/gradle.properties#L1

https://github.com/IntegratedAlarmSystem-Group/ias-plugins/blob/f2def430fb34c94b8b5b10e44649ba99b6d33816/AlmaWeatherStationPlugin/settings.gradle#L1

To be used in our uploadArchives task:

![image](https://user-images.githubusercontent.com/4417761/37421654-9b9cdf34-2798-11e8-86e8-cc1b3f70deaa.png)

To upload the artifact to Artifactory.

![image](https://user-images.githubusercontent.com/4417761/37421676-ab850732-2798-11e8-9ba7-eb269a7389fa.png)
